# Generated by Django 5.0.4 on 2024-04-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='item_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
