# Generated by Django 5.0.4 on 2024-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_cartitems_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
