# Generated by Django 5.0.4 on 2024-06-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subTotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
