# Generated by Django 5.0.4 on 2024-06-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalQty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
