# Generated by Django 5.0.4 on 2024-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_cart_totalqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
