# Generated by Django 5.0.4 on 2024-04-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_colorvariants_sizevariants_products_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariants',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sizevariants',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
