# Generated by Django 5.0.4 on 2024-04-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_colorvariants_price_sizevariants_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariants',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sizevariants',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
