# Generated by Django 5.0.4 on 2024-04-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_colorvariants_discount_sizevariants_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariants',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorvariants',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sizevariants',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sizevariants',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
