# Generated by Django 5.0.4 on 2024-04-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_products_manual_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='manual_discount',
        ),
        migrations.AddField(
            model_name='colorvariants',
            name='manual_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sizevariants',
            name='manual_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
