# Generated by Django 5.0.4 on 2024-04-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_products_manual_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_manual_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
