# Generated by Django 5.0.4 on 2024-04-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_products_product_manual_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
