# Generated by Django 5.0.4 on 2024-06-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_expired',
            new_name='is_expire',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=10),
        ),
    ]
