# Generated by Django 5.0.4 on 2024-06-11 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_is_expired_coupon_is_expire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 5, 29, 46, 455913, tzinfo=datetime.timezone.utc)),
        ),
    ]
