# Generated by Django 5.0.4 on 2024-06-11 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_coupon_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 11, 5, 35, 47, 57732, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
