# Generated by Django 5.0.4 on 2024-06-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='time_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
